"files": [
  {
    "source": "/i18n/en/**/*.json",
    "translation": "/i18n/%two_letters_code%/**/%original_file_name%"
  },
  {
    "source": "/i18n/en/**/*.md",
    "translation": "/i18n/%two_letters_code%/**/%original_file_name%",
    "ignore": [
      "/**/_category_.json",
      "/**/docusaurus-plugin-content-blog/*"
    ]
  }
]
