module.exports = {
  sidebar: [
    {
      type: "doc",
      label: "Welcome",
      id: "welcome",
    },
    {
      type: "category",
      label: "Protocol",
      items: [
        {
          type: "autogenerated",
          dirName: "protocol",
        },
      ],
    },
    {
      type: "category",
      label: "Token",
      items: [
        {
          type: "autogenerated",
          dirName: "token",
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "doc",
          id: "api/rest-api",
        },
        {
          type: "doc",
          id: "api/hedgehog",
        },
        {
          type: "category",
          label: "Audius SDK",
          items: [
            {
              type: "doc",
              id: "api/sdk/index",
            },
            {
              type: "doc",
              id: "api/sdk/classes/TracksApi",
            },
            {
              type: "doc",
              id: "api/sdk/classes/UsersApi",
            },
            {
              type: "doc",
              id: "api/sdk/classes/PlaylistsApi",
            },
            {
              type: "doc",
              id: "api/sdk/classes/ResolveApi",
            },
            {
              type: "doc",
              id: "api/sdk/oauth",
            },
            {
              type: "category",
              label: "Full Reference",
              items: [
                {
                  type: "category",
                  label: "Interfaces",
                  items: [
                    {
                      type: "autogenerated",
                      dirName: "api/sdk/interfaces",
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Enums",
                  items: [
                    {
                      type: "autogenerated",
                      dirName: "api/sdk/enums",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          type: "doc",
          id: "api/log-in-with-audius",
        },
      ],
    },
  ],
};
